"""Generate the faceted crystal mesh for XVECTOR demo 6.

By Dag Erik Hagesæter / Retro Erik using Codex in VS Code
"""

from math import cos, pi, sin
from pathlib import Path


SECTORS = 20
# (height, radius): pointed ends and a broad, deliberately angular waist.
RINGS = ((104, 0), (68, 43), (19, 96), (-20, 96), (-69, 43), (-104, 0))
OUTPUT = Path(__file__).with_name("xga_crystal_mesh.inc")


def index(ring: int, sector: int) -> int:
    return ring * SECTORS + sector % SECTORS


lines = [
    "; Generated by make_vector_crystal.py; 20 sectors, 6 profile rings.",
    "; By Dag Erik Hagesæter / Retro Erik using Codex in VS Code",
    "crystal_vertices:",
]
for height, radius in RINGS:
    for sector in range(SECTORS):
        angle = 2 * pi * sector / SECTORS
        lines.append(f"    dw {round(radius*cos(angle))},{height},{round(radius*sin(angle))}")

lines.append("crystal_quads:")
for ring in range(len(RINGS) - 1):
    for sector in range(SECTORS):
        a = index(ring, sector)
        b = index(ring + 1, sector)
        c = index(ring + 1, sector + 1)
        d = index(ring, sector + 1)
        # Paired facets share a color family; adjoining facets catch light differently.
        color = 12 + ((sector // 2 + ring * 3) % 8)
        lines.append(f"    db {a},{b},{c},{d},{color}")
lines.append("crystal_quads_end:")

OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"Wrote {OUTPUT.name}: {SECTORS * len(RINGS)} vertices, "
      f"{SECTORS * (len(RINGS) - 1)} facets")
