"""Generate compact point shapes and circle masks for XBALLS mode 7.

By Dag Erik Hagesæter / Retro Erik using Codex in VS Code
"""
from math import cos, hypot, pi, sin
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE / "assets"
COUNT = 96
NAMES = ("TREE", "GIRAFFE", "BIRD", "FISH", "DRAGON")

# Color classes: bark, leaves, gold, orange, red, cyan, blue, purple.
RGB = ((151, 91, 49), (105, 235, 148), (249, 212, 82),
       (255, 150, 57), (250, 75, 90), (72, 227, 240),
       (70, 126, 235), (219, 105, 232))


def ellipse(cx, cy, rx, ry, count, color, size, start=0, stop=2 * pi):
    return [(round(cx + rx * cos(start + (stop - start) * i / count)),
             round(cy + ry * sin(start + (stop - start) * i / count)),
             size if isinstance(size, int) else size[i % len(size)], color)
            for i in range(count)]


def path(points, count, color, size):
    lengths = [hypot(x1 - x0, y1 - y0)
               for (x0, y0), (x1, y1) in zip(points, points[1:])]
    total = sum(lengths)
    result = []
    for i in range(count):
        distance = total * i / max(1, count - 1)
        for segment, length in enumerate(lengths):
            if distance <= length or segment == len(lengths) - 1:
                x0, y0 = points[segment]
                x1, y1 = points[segment + 1]
                t = min(1, distance / length) if length else 0
                result.append((round(x0 + (x1 - x0) * t),
                               round(y0 + (y1 - y0) * t),
                               size if isinstance(size, int)
                               else size[i % len(size)], color))
                break
            distance -= length
    return result


shapes = []

# The groups have the same lengths in all five figures. Corresponding groups
# tend to move together, which makes the transition read as a morph.
tree = []
tree += ellipse(320, 168, 110, 75, 24, 1, (2, 3))
tree += path([(320, 382), (320, 215)], 20, 0, (1, 2))
tree += path([(320, 300), (265, 190), (215, 155)], 10, 0, 1)
tree += path([(320, 295), (380, 190), (430, 160)], 10, 0, 1)
tree += path([(320, 365), (270, 400), (225, 408)], 8, 0, 1)
tree += path([(320, 365), (370, 400), (415, 408)], 8, 0, 1)
tree += [(round(245 + (i % 4) * 48 + (i // 4 % 2) * 12),
          round(130 + (i // 4) * 27), i % 2, 4 if i % 3 else 2)
         for i in range(16)]
shapes.append(tree)

giraffe = []
giraffe += ellipse(304, 255, 103, 53, 24, 3, (2, 3))
giraffe += path([(363, 246), (375, 138), (394, 104)], 20, 3, (1, 2))
for x in (225, 273, 338, 388):
    giraffe += path([(x, 285), (x - 6, 402)], 5, 3, 1)
giraffe += ellipse(406, 94, 35, 20, 16, 3, (1, 2))
giraffe += [(226 + (i % 4) * 43, 230 + (i // 4 % 3) * 22,
             0 if i % 3 else 1, 0) for i in range(12)]
giraffe += path([(205, 250), (170, 235), (155, 265)], 4, 0, 1)
shapes.append(giraffe)

bird = []
bird += ellipse(316, 251, 79, 54, 24, 6, (2, 3))
bird += path([(282, 228), (168, 106), (212, 206), (260, 238)],
             20, 5, (1, 2))
bird += path([(348, 227), (477, 105), (433, 213), (367, 243)],
             20, 5, (1, 2))
bird += path([(267, 282), (196, 354), (224, 302), (251, 279)],
             16, 7, (1, 2))
bird += ellipse(392, 218, 31, 27, 12, 6, 2)
bird += path([(423, 218), (473, 226), (425, 239)], 4, 2, 1)
shapes.append(bird)

fish = []
fish += ellipse(321, 249, 125, 66, 24, 5, (2, 3))
fish += path([(285, 190), (309, 129), (344, 188)], 20, 6, (1, 2))
fish += path([(273, 306), (310, 356), (342, 303)], 20, 6, (1, 2))
fish += path([(198, 248), (102, 179), (119, 249), (102, 319),
              (198, 248)], 16, 6, (1, 2))
fish += [(394, 226, 2, 2), (398, 225, 0, 6),
         (264, 236, 1, 2), (292, 259, 1, 2), (317, 226, 1, 2),
         (341, 270, 1, 2), (364, 242, 1, 2), (286, 276, 1, 6),
         (245, 254, 1, 6), (331, 247, 1, 6), (360, 280, 1, 6),
         (392, 262, 1, 6), (426, 246, 1, 6), (379, 291, 1, 6),
         (303, 221, 1, 6), (262, 284, 1, 6)]
shapes.append(fish)

dragon = []
dragon += ellipse(300, 269, 105, 55, 24, 1, (2, 3))
dragon += path([(360, 246), (392, 165), (423, 133), (462, 145)],
               20, 1, (1, 2))
dragon += path([(314, 223), (215, 95), (254, 195), (335, 237),
                (401, 107), (367, 229)], 20, 7, (1, 2))
dragon += path([(219, 269), (146, 283), (106, 374), (140, 353)],
               16, 1, (1, 2))
dragon += path([(438, 128), (452, 91), (466, 128)], 6, 2, 1)
dragon += path([(459, 158), (510, 172), (534, 153)], 6, 4, (0, 1))
dragon += path([(269, 312), (255, 396)], 4, 0, 1)
shapes.append(dragon)

assert len(shapes) == 5 and all(len(shape) == COUNT for shape in shapes), [
    len(shape) for shape in shapes]

with (HERE / "xga_morph_shapes.inc").open("w", encoding="ascii") as out:
    out.write("; Five figures, 96 packed 3-byte balls each; generated by make_morph_assets.py.\n")
    out.write("; Bits 0..9 x, 10..18 y, 19..20 size, 21..23 color.\n")
    out.write("morph_shapes:\n")
    for name, shape in zip(NAMES, shapes):
        out.write(f"; {name}\n")
        for x, y, size, color in shape:
            assert 16 <= x < 624 and 16 <= y < 464 and 0 <= size < 4
            assert 0 <= color < 8
            value = x | (y << 10) | (size << 19) | (color << 21)
            out.write("    db " + ",".join(map(str, (
                value & 255, (value >> 8) & 255,
                (value >> 16) & 255))) + "\n")

masks = bytearray()
for diameter in (8, 16, 24, 32):
    radius = diameter / 2 - 0.5
    for y in range(32):
        row = [0] * 4
        for x in range(32):
            if hypot(x - 15.5, y - 15.5) < radius:
                row[x // 8] |= 1 << (x & 7)
        masks.extend(row)
assert len(masks) == 512
(ASSETS / "xga_morph_masks.bin").write_bytes(masks)

with (HERE / "xga_morph_palette.inc").open("w", encoding="ascii") as out:
    out.write("; Palette entries 128..135: eight morph colors.\n")
    for rgb in RGB:
        out.write("    db " + ",".join(map(str, rgb)) + "\n")

try:
    from PIL import Image, ImageDraw
except ImportError:
    pass
else:
    preview = Image.new("RGB", (960, 480), (7, 28, 34))
    draw = ImageDraw.Draw(preview)
    for shape_index, (name, shape) in enumerate(zip(NAMES, shapes)):
        ox = shape_index % 3 * 320
        oy = shape_index // 3 * 240
        for x, y, size, color in shape:
            px, py = ox + x / 2, oy + y / 2
            r = (8, 16, 24, 32)[size] / 4
            draw.ellipse((px - r, py - r, px + r, py + r), fill=RGB[color])
        draw.text((ox + 6, oy + 5), name, fill=(255, 255, 255))
    preview.save(ASSETS / "xga_morph_shapes_preview.png")

print("Generated five 96-ball morph shapes and four size masks")
