"""Generate a compact checkered sphere mesh for the XGA Boing Ball.

By Dag Erik Hagesæter / Retro Erik using Codex in VS Code
"""

from math import cos, pi, sin
from pathlib import Path


LONGITUDES = 16
LATITUDES = 8
RADIUS = 74
OUTPUT = Path(__file__).with_name("xga_boing_mesh.inc")


def index(longitude: int, latitude: int) -> int:
    return (longitude % LONGITUDES) * LATITUDES + latitude


lines = [
    "; Generated by make_vector_boing.py; 16 longitudes x 8 latitudes.",
    "; By Dag Erik Hagesæter / Retro Erik using Codex in VS Code",
    "boing_vertices:",
]
for longitude in range(LONGITUDES):
    u = 2 * pi * longitude / LONGITUDES
    for latitude in range(LATITUDES):
        v = -pi / 2 + pi * latitude / (LATITUDES - 1)
        x = round(RADIUS * cos(v) * cos(u))
        y = round(RADIUS * sin(v))
        z = round(RADIUS * cos(v) * sin(u))
        lines.append(f"    dw {x},{y},{z}")

lines.append("boing_quads:")
for longitude in range(LONGITUDES):
    for latitude in range(LATITUDES - 1):
        a = index(longitude, latitude)
        b = index(longitude + 1, latitude)
        c = index(longitude + 1, latitude + 1)
        d = index(longitude, latitude + 1)
        color = 7 if ((longitude + latitude) & 1) else 1
        lines.append(f"    db {a},{b},{c},{d},{color}")

OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"Wrote {OUTPUT.name}: {LONGITUDES * LATITUDES} vertices, "
      f"{LONGITUDES * (LATITUDES - 1)} quads")
