"""Generate XGA ball art, masks, palette and an integer sine table.

By Dag Erik Hagesæter / Retro Erik using Codex in VS Code
"""
from math import cos, sin, pi, sqrt
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIZE = 48
pixels = bytearray()
mask = bytearray()
for y in range(SIZE):
    mask_row = [0] * 6
    for x in range(SIZE):
        nx = (x - 23.5) / 23.5
        ny = (y - 23.5) / 23.5
        r2 = nx * nx + ny * ny
        if r2 >= 1:
            pixels.append(0)
            continue
        mask_row[x // 8] |= 1 << (x & 7)  # XGA one-bit Intel pixel order
        nz = sqrt(1 - r2)
        light = max(0, -0.42 * nx - 0.58 * ny + 0.69 * nz)
        shade = min(15, max(1, round(2 + 13 * light)))
        pixels.append(shade)
    mask.extend(mask_row)

assert len(pixels) == 2304 and len(mask) == 288
(HERE / "assets" / "xga_ball48.bin").write_bytes(pixels)
(HERE / "assets" / "xga_ball48_mask.bin").write_bytes(mask)

values = [round(127 * sin(i * 2 * pi / 256)) for i in range(256)]
# The cosine lookup can address positions 256..319 without a wrap branch.
values.extend(values[:64])
with (HERE / "xga_balls_sine.inc").open("w", encoding="ascii") as out:
    out.write("; Signed sine, 256 positions; generated by make_balls_assets.py.\n")
    out.write("sine_table:\n")
    for start in range(0, len(values), 16):
        out.write("    db " + ",".join(str(n) for n in values[start:start + 16]) + "\n")
print("Generated ball, mask and sine table")

# Four 24x24 color variants for the dense, multi-lane sine display. One
# shared circular mask is used for every copy; the source Y selects a color.
SMALL = 24
lane_colors = [(0, 205, 230), (255, 104, 112),
               (248, 203, 56), (104, 231, 145)]
small_pixels = bytearray()
small_mask = bytearray()
for lane, (red, green, blue) in enumerate(lane_colors):
    for y in range(SMALL):
        mask_row = [0] * (SMALL // 8)
        for x in range(SMALL):
            nx = (x - 11.5) / 11.5
            ny = (y - 11.5) / 11.5
            r2 = nx * nx + ny * ny
            if r2 >= 1:
                small_pixels.append(0)
                continue
            mask_row[x // 8] |= 1 << (x & 7)
            nz = sqrt(1 - r2)
            light = max(0, -0.42 * nx - 0.58 * ny + 0.69 * nz)
            shade = min(15, max(1, round(2 + 13 * light)))
            small_pixels.append(32 + 16 * lane + shade)
        if lane == 0:
            small_mask.extend(mask_row)

assert len(small_pixels) == 4 * SMALL * SMALL
assert len(small_mask) == SMALL * SMALL // 8
(HERE / "assets" / "xga_ball24x4.bin").write_bytes(small_pixels)
(HERE / "assets" / "xga_ball24_mask.bin").write_bytes(small_mask)

with (HERE / "xga_dense_palette.inc").open("w", encoding="ascii") as out:
    out.write("; Indices 32..95, generated by make_balls_assets.py.\n")
    for red, green, blue in lane_colors:
        for shade in range(16):
            # The highlight approaches white, the edge remains saturated.
            value = shade / 15
            scale = 0.23 + 0.73 * value
            white = 0.70 * max(0.0, (value - 0.77) / 0.23)
            rgb = [min(255, round(channel * scale * (1 - white)
                                  + 255 * white))
                   for channel in (red, green, blue)]
            out.write("    db " + ",".join(map(str, rgb)) + "\n")
print("Generated 24x24 dense-snake assets and palette")

# Flat, dithered circles for the perspective orbit. XGA's pattern map is
# one bit per pixel: present bits receive a palette color, clear bits retain
# the old screen pixel. This suggests translucency, without RGB blending.
orbit_sizes = tuple(range(80, 185, 8))
bayer4 = ((0, 8, 2, 10), (12, 4, 14, 6),
          (3, 11, 1, 9), (15, 7, 13, 5))
orbit_masks = bytearray()
mask_offsets = {}
for size_index, size in enumerate(orbit_sizes):
    mask_offsets[size] = len(orbit_masks)
    radius = size / 2 - 1
    for y in range(size):
        row = [0] * (size // 8)
        for x in range(size):
            dx = x - (size - 1) / 2
            dy = y - (size - 1) / 2
            rr = sqrt(dx * dx + dy * dy)
            if rr >= radius:
                continue
            # Vary the Bayer phase between sizes while storing only one
            # mask per diameter; this doubles the number of sizes in the COM.
            sample = bayer4[(y + 2 * (size_index & 1)) & 3][
                (x + (size_index >> 1)) & 3]
            if rr >= radius - 1.5 or sample < 10:
                row[x // 8] |= 1 << (x & 7)
        orbit_masks.extend(row)
assert len(orbit_masks) == sum(size * size // 8 for size in orbit_sizes)
(HERE / "assets" / "xga_orbit_masks.bin").write_bytes(orbit_masks)

orbit_colors = ((104, 225, 127), (45, 221, 236), (231, 85, 238),
                (248, 216, 67), (255, 125, 111), (140, 142, 255),
                (229, 227, 215), (7, 28, 34))
with (HERE / "xga_orbit_palette.inc").open("w", encoding="ascii") as out:
    out.write("; Indices 96..103 (last = backdrop), generated by make_balls_assets.py.\n")
    for rgb in orbit_colors:
        out.write("    db " + ",".join(map(str, rgb)) + "\n")

axes = ((145, 0, 0), (-145, 0, 0), (0, 145, 0),
        (0, -145, 0), (0, 0, 145), (0, 0, -145))
with (HERE / "xga_orbit3d_frames.inc").open("w", encoding="ascii") as out:
    out.write("; 512 depth-sorted frames: 9-bit x, 9-bit y, packed size/color.\n")
    out.write("; Generated by make_balls_assets.py; values fit the 16-bit COM.\n")
    out.write("orbit_mask_offsets:\n")
    for size in orbit_sizes:
        out.write(f"    dw {mask_offsets[size]}\n")
    out.write("orbit_sizes:\n")
    out.write("    db " + ",".join(map(str, orbit_sizes)) + "\n")
    out.write("orbit3d_frames:\n")
    for frame in range(512):
        theta = frame * 2 * pi / 512
        phi = frame * 4 * pi / 512
        points = []
        for ident, (x, y, z) in enumerate(axes):
            x1 = x * cos(theta) + z * sin(theta)
            z1 = -x * sin(theta) + z * cos(theta)
            y2 = y * cos(phi) - z1 * sin(phi)
            z2 = y * sin(phi) + z1 * cos(phi)
            scale = 330 / (330 - z2)
            nominal_size = 115 * scale
            size = min(orbit_sizes, key=lambda candidate:
                       abs(candidate - nominal_size))
            left = round(320 + x1 * scale - size / 2)
            top = round(240 + y2 * scale - size / 2)
            points.append((z2, left, top, size, ident))
        points.append((0, 320 - 72, 240 - 72, 144, 6))
        points.sort(key=lambda item: item[0])
        for depth, left, top, size, ident in points:
            packed = orbit_sizes.index(size) * 8 + ident
            assert 0 <= packed < 128
            assert 0 <= left < 512 and 0 <= top < 512
            position = left | (top << 9)
            out.write(f"    db {position & 255},{(position >> 8) & 255},{(position >> 16) & 255},{packed}\n")
assert len(orbit_masks) + 2304 + 288 + 2304 + 72 + 2 * 307200 < 655360
print("Generated 14 orbit masks and 512-frame 3D orbit table")

# A 33x24 dot matrix keeps the Norwegian flag's 22:16 proportions. The
# 16x16 colored ball source and its shared circular mask fit in VRAM bank 10.
FLAG_SIZE = 16
flag_bases = ((235, 30, 55), (240, 243, 247), (32, 72, 174))
flag_pixels = bytearray()
flag_mask = bytearray()
for color_index in range(3):
    for y in range(FLAG_SIZE):
        row = [0] * (FLAG_SIZE // 8)
        for x in range(FLAG_SIZE):
            nx = (x - 7.5) / 7.5
            ny = (y - 7.5) / 7.5
            r2 = nx * nx + ny * ny
            if r2 >= 1:
                flag_pixels.append(0)
                continue
            row[x // 8] |= 1 << (x & 7)
            nz = sqrt(1 - r2)
            light = max(0, -0.42 * nx - 0.58 * ny + 0.69 * nz)
            shade = min(7, max(1, round(1 + 6 * light)))
            flag_pixels.append(104 + 8 * color_index + shade)
        if color_index == 0:
            flag_mask.extend(row)
assert len(flag_pixels) == 768 and len(flag_mask) == 32
(HERE / "assets" / "xga_flag_balls.bin").write_bytes(flag_pixels)
(HERE / "assets" / "xga_flag_mask.bin").write_bytes(flag_mask)
with (HERE / "xga_flag_palette.inc").open("w", encoding="ascii") as out:
    out.write("; Indices 104..127, generated by make_balls_assets.py.\n")
    for red, green, blue in flag_bases:
        for shade in range(8):
            value = shade / 7
            scale = 0.25 + 0.75 * value
            white = 0.30 * max(0.0, (value - 0.75) / 0.25)
            rgb = [min(255, round(channel * scale * (1 - white)
                                  + 255 * white))
                   for channel in (red, green, blue)]
            out.write("    db " + ",".join(map(str, rgb)) + "\n")

flag_colors = []
for row in range(24):
    v = row * 16 // 24
    colors = []
    for col in range(33):
        u = col * 22 // 33
        blue = 7 <= u < 9 or 7 <= v < 9
        white = 6 <= u < 10 or 6 <= v < 10
        colors.append(2 if blue else 1 if white else 0)
    flag_colors.extend(colors)
with (HERE / "xga_flag_colors.inc").open("w", encoding="ascii") as out:
    out.write("; 33x24 Norwegian cross: 0 red, 1 white, 2 blue.\n")
    out.write("flag_colors:\n")
    for row in range(24):
        out.write("    db " + ",".join(map(str,
                  flag_colors[row * 33:(row + 1) * 33])) + "\n")
assert len(flag_colors) == 792
print("Generated 792-ball Norwegian flag assets and color layout")
