"""Generate the compact torus mesh used by XVECTOR.COM mode 4.

By Dag Erik Hagesæter / Retro Erik using Codex in VS Code
"""

from math import cos, pi, sin
from pathlib import Path


MAJOR_SEGMENTS = 16
MINOR_SEGMENTS = 8
MAJOR_RADIUS = 108
TUBE_RADIUS = 42
OUTPUT = Path(__file__).with_name("xga_torus_mesh.inc")


def vertex(major: int, minor: int) -> tuple[int, int, int]:
    u = 2 * pi * major / MAJOR_SEGMENTS
    v = 2 * pi * minor / MINOR_SEGMENTS
    radius = MAJOR_RADIUS + TUBE_RADIUS * cos(v)
    return (round(radius * cos(u)), round(TUBE_RADIUS * sin(v)),
            round(radius * sin(u)))


def index(major: int, minor: int) -> int:
    return (major % MAJOR_SEGMENTS) * MINOR_SEGMENTS + minor % MINOR_SEGMENTS


lines = [
    "; Generated by make_vector_torus.py; 16 major x 8 tube segments.",
    "; By Dag Erik Hagesæter / Retro Erik using Codex in VS Code",
    "torus_vertices:",
]
for major in range(MAJOR_SEGMENTS):
    for minor in range(MINOR_SEGMENTS):
        x, y, z = vertex(major, minor)
        lines.append(f"    dw {x},{y},{z}")

lines.append("torus_quads:")
for major in range(MAJOR_SEGMENTS):
    for minor in range(MINOR_SEGMENTS):
        a = index(major, minor)
        b = index(major + 1, minor)
        c = index(major + 1, minor + 1)
        d = index(major, minor + 1)
        color = 2 + ((major + 2 * minor) & 7)
        lines.append(f"    db {a},{b},{c},{d},{color}")
lines.append("torus_quads_end:")
lines.append("torus_order:")
for first in range(0, MAJOR_SEGMENTS * MINOR_SEGMENTS, 16):
    lines.append("    db " + ",".join(str(value) for value in range(first, first + 16)))

OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"Wrote {OUTPUT.name}: {MAJOR_SEGMENTS * MINOR_SEGMENTS} vertices, "
      f"{MAJOR_SEGMENTS * MINOR_SEGMENTS} quads")
