"""Generate compact 48x48 XGA ball and mask assets plus an integer sine table.

By Dag Erik Hagesæter / Retro Erik using Codex in VS Code
"""
from math import sin, pi, sqrt
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIZE = 48
pixels = bytearray()
mask = bytearray()
for y in range(SIZE):
    mask_row = [0] * 6
    for x in range(SIZE):
        nx = (x - 23.5) / 23.5
        ny = (y - 23.5) / 23.5
        r2 = nx * nx + ny * ny
        if r2 >= 1:
            pixels.append(0)
            continue
        mask_row[x // 8] |= 1 << (x & 7)  # XGA one-bit Intel pixel order
        nz = sqrt(1 - r2)
        light = max(0, -0.42 * nx - 0.58 * ny + 0.69 * nz)
        shade = min(15, max(1, round(2 + 13 * light)))
        pixels.append(shade)
    mask.extend(mask_row)

assert len(pixels) == 2304 and len(mask) == 288
(HERE / "assets" / "xga_ball48.bin").write_bytes(pixels)
(HERE / "assets" / "xga_ball48_mask.bin").write_bytes(mask)

values = [round(127 * sin(i * 2 * pi / 256)) for i in range(256)]
# The cosine lookup can address positions 256..319 without a wrap branch.
values.extend(values[:64])
with (HERE / "xga_balls_sine.inc").open("w", encoding="ascii") as out:
    out.write("; Signed sine, 256 positions; generated by make_balls_assets.py.\n")
    out.write("sine_table:\n")
    for start in range(0, len(values), 16):
        out.write("    db " + ",".join(str(n) for n in values[start:start + 16]) + "\n")
print("Generated ball, mask and sine table")
