# makefile MAKE V2.0 or higher
.autodepend

# to enable debugging information, set "DEBUG" to "yes"
DEBUG = no

# define all object files that make up the executable
OBJS = slidetxt.obj fontdata.obj

##############################################################################

!if ($(DEBUG) == yes)
TLINKDEBUG = /v
!endif

##############################################################################

.asm.obj:
    tasm /m /ml /zi $<

##############################################################################

slidetxt.exe:   $(OBJS) makefile
        tlink /x $(TLINKDEBUG) @&&|
$(OBJS)
slidetxt.exe
slidetxt.map

|
        !if ($(DEBUG) != yes)
        pklite slidetxt
        !endif

##############################################################################

fontdata.jlf:   fontdata.pcx fontdata.cfg
                pcx2fnt fontdata

##############################################################################

fontdata.obj:   fontdata.jlf
                2obj b fontdata.jlf MyData:FontData

##############################################################################
