# makefile MAKE V2.0 or higher
.autodepend

# to enable debugging information, set "DEBUG" to "yes"
DEBUG = no

# define all object files that make up the executable
OBJS = stretch.obj fontdata.obj heartimg.obj heartpal.obj

##############################################################################

!if ($(DEBUG) == yes)
TLINKDEBUG = /v
!endif

##############################################################################

.asm.obj:
    tasm /ml /m /zi $<

##############################################################################

stretch.exe:    $(OBJS) makefile
        tlink /x $(TLINKDEBUG) @&&|
$(OBJS)
stretch.exe
stretch.map

|
        !if ($(DEBUG) != yes)
        pklite stretch
        !endif

##############################################################################

fontdata.jlf:   fontdata.pcx fontdata.cfg
                pcx2fnt fontdata

##############################################################################

fontdata.obj:   fontdata.jlf
                2obj b fontdata.jlf MyData:FontData

##############################################################################

heartimg.obj:   heart.pcx
                2obj p /d heart.pcx heartimg.obj MyData:HeartImage

##############################################################################

heartpal.obj:   heart.pcx
                2obj v /d heart.pcx heartpal.obj MyData:HeartPalette

##############################################################################
